FROM --platform=linux/arm64 docker.io/caproni60/financial:base-latest

LABEL entrypoint "update_stocks.py"

COPY src /code/src

COPY update_stocks.py /code/

RUN chmod +x /code/update_stocks.py

ENTRYPOINT ["python", "update_stocks.py"]