FROM --platform=linux/arm64 docker.io/caproni60/financial:base-latest

LABEL entrypoint="test_cronjob.py"

COPY src /code/src

COPY test_cronjob.py /code/

RUN chmod +x /code/test_cronjob.py

ENTRYPOINT ["python", "test_cronjob.py"]