FROM --platform=linux/arm64 docker.io/caproni60/financial:base-latest

LABEL entrypoint="populate_reference_data.py"

COPY src /code/src

COPY populate_reference_data.py /code/

RUN chmod +x /code/populate_reference_data.py

ENTRYPOINT ["python", "populate_reference_data.py"]