name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for multi-arch support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          # Change this to point to your subdirectory context
          context: . 
          # Adjust the Dockerfile path as well
          file: ./dockerfiles/Dockerfile.run-models 
          platforms: linux/arm64
          push: true
          tags: docker.io/caproni60/financial:run-models-latest

      # Optional: Log out from Docker Hub
      - name: Log out from Docker Hub
        run: docker logout
