name: Build and Push Container Image with Buildah

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions runs on Ubuntu by default

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Buildah
      - name: Install Buildah
        run: |
          sudo apt-get update
          sudo apt-get -y install buildah

      # Step 3: Log in to Docker Hub (for pushing the image)
      - name: Log in to Docker Hub
        run: |
          buildah login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      # Step 4: Build the container image using Buildah
      - name: Build the container image
        run: |
          buildah bud --arch arm --os linux -f ./dockerfiles/Dockerfile.update-stocks -t docker.io/caproni60/financial:update-stocks-latest .

      # Step 5: Push the image to Docker Hub
      - name: Push the image to Docker Hub
        run: |
          buildah push docker.io/caproni60/financial:update-stocks-latest
          
      # Optional: Log out from Docker Hub
      - name: Log out from Docker Hub
        run: |
          buildah logout docker.io
